[build]
  publish = "public"
  command = "apt-get update && apt-get install -y default-libmysqlclient-dev && npm run build"

[build.environment]
  MYSQLCLIENT_VERSION = "8.0"

[[plugins]]
  package = "@netlify/plugin-functions-install-core-binaries"

[[redirects]]
  from = "/*"
  to = "/LOGINPrincipal.php"
  status = 200
