[build]
  publish = "proyecto"
  command = "apt-get update && apt-get install -y libmariadb-dev && npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core-binaries"

[[redirects]]
  from = "/*"
  to = "/LOGINPrincipal.php"
  status = 200
