[build]
  publish = "proyecto"
  command = "npm run build"

[build.command]
  - apt-get update && apt-get install -y libmariadb-dev

[[plugins]]
  package = "@netlify/plugin-functions-install-core-binaries"

[[redirects]]
  from = "/*"
  to = "/LOGINPrincipal.php"
  status = 200
